### ISSUE TITLE
does not work with mariadb 10.4 and TLS

### ISSUE THREAD

**Issue by nerijus** [Apskaita5/Apskaita5#4]
```
Klaida. Nepavyko prisijungti prie duomenų bazės: The handshake failed due to an unexpected packet format.

Programos versija: Nenurodyta
Windows versija: Microsoft Windows NT 6.2.9200.0
.NET versija: 2.0.50727.9151
Klaidos duomenys:
Klaidos tipas: Csla.DataPortalException
Klaidos tekstas:
DataPortal.Fetch failed (System.Exception: Klaida. Nepavyko prisijungti prie duomenų bazės: The handshake failed due to an unexpected packet format. ---> System.IO.IOException: The handshake failed due to an unexpected packet format.
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
...
```
The program should be recompiled to support TLS 1.2 - https://onloupe.com/blog/enabling-tls-1-2-with-dotnet-2-and-later/
Unsecure workaround is to enable TLS 1.0 in mariadb:
```
[mariadb]
tls_version = TLSv1.0,TLSv1.1,TLSv1.2,TLSv1.3
```

**Comment by Apskaita5** [comment]
Unfortunatelly cannot do that. Too many users on XP, cannot use .net v higher than 3.5.

**Comment by nerijus** [comment]
Then it would be nice to have 2 installers - one for XP and one for newer OSes. BTW, XP is unsupported from 2014 or smth, are there really so many users left?

**Comment by nerijus** [comment]
BTW, https://onloupe.com/blog/enabling-tls-1-2-with-dotnet-2-and-later/ has:
```How to use TLS 1.2 with HttpClient in .NET 2.0 - .NET 4.0
```
So it should support even .NET 2.0.

**Comment by Apskaita5** [comment]
As per error reports over last year a bit more than half of the users are still on xp. It's too hard for me alone to support multiple builds.
In this case connection is initiated not by the application but by mysqlconnector. Not sure what method it uses and whether it's possible to use the workaround.

**Comment by nerijus** [comment]
TLS 1.0 is weak and is being deprecated - https://www.zdnet.com/article/browsers-to-block-access-to-https-sites-using-tls-1-0-and-1-1-starting-this-month/
So supporting any newer protocol would be nice anyway (and would probably be necessity quite soon).

**Comment by Apskaita5** [comment]
I know :)
However, the application itself got technologically obsolete. As of the current version the only major upgrade is going to be the refactoring of inventory module. Minor upgrades only for tax legislation changes.
I've started work on vNext from scratch. New, way more flexible and efficient DB architecture is documented on codeproject (https://www.codeproject.com/script/Articles/MemberArticles.aspx?amid=3605675).
New abstract SQL DAL with a small ORM is one of my repositories here.
For now I'm developing a small .net core app for my office using clean architecture. Learning by doing. Should be complete in a week or two. Looks like the architecture will fit financial accounting very nice as well. If success, will write a code gen tool to transform the current version BL to domain and services layers of CA. In a year or two, vNext will be ready :)
Any help is welcome.

**Comment by Apskaita5** [comment]
Solved in the last update (will upload in minutes).

**Comment by viaruc** [comment]
Used your installation package from the wiki. Issue still persists.

**Comment by nerijus** [comment]
> Solved in the last update (will upload in minutes).

Unfortunately it still requires tls v1. Sniffer output on a working CentOS 8 system with `tls_version = TLSv1.0,TLSv1.1,TLSv1.2,TLSv1.3`:
```
   18 9.199050729 192.168.1.38 → 192.168.1.37 TLSv1 149 Client Hello
   19 9.199080805 192.168.1.37 → 192.168.1.38 TCP 54 3306 → 52711 [ACK] Seq=94 Ack=132 Win=29312 Len=0
   20 9.212009124 192.168.1.37 → 192.168.1.38 TLSv1 2717 Server Hello, Certificate, Server Key Exchange, Certificate Request, Server Hello Done
   21 9.213925698 192.168.1.38 → 192.168.1.37 TCP 60 52711 → 3306 [ACK] Seq=132 Ack=2757 Win=262656 Len=0
   22 9.224085414 192.168.1.38 → 192.168.1.37 TLSv1 162 Certificate, Client Key Exchange, Change Cipher Spec, Encrypted Handshake Message
   23 9.225459824 192.168.1.37 → 192.168.1.38 TLSv1 304 New Session Ticket, Change Cipher Spec, Encrypted Handshake Message
```
On CentOS 9 it does not work because there are no mutually supported ciphers or TLS protocol versions:
```
   12 2.743188951 192.168.1.38 → 192.168.1.97 TLSv1 149 Client Hello
   13 2.743279163 192.168.1.97 → 192.168.1.38 TCP 54 3306 → 52729 [ACK] Seq=94 Ack=132 Win=32128 Len=0
   14 2.743512872 192.168.1.97 → 192.168.1.38 TLSv1 61 Alert (Level: Fatal, Description: Protocol Version)
```
In both cases Apskaita5 tries `TLSv1` only.

A connection from `mysql` command line client uses `TLSv1.3`:
```
   11 0.638918601 192.168.1.37 → 192.168.1.97 TLSv1 583 Client Hello
   12 0.638983394 192.168.1.97 → 192.168.1.37 TCP 66 3306 → 57178 [ACK] Seq=94 Ack=554 Win=31872 Len=0 TSval=2689948724 TSecr=2674494919
   13 0.645730356 192.168.1.97 → 192.168.1.37 TLSv1.3 2953 Server Hello, Change Cipher Spec, Application Data, Application Data, Application Data, Application Data, Application Data
   14 0.646097482 192.168.1.37 → 192.168.1.97 TCP 66 57178 → 3306 [ACK] Seq=554 Ack=2981 Win=35072 Len=0 TSval=2674494926 TSecr=2689948731
   15 0.647079250 192.168.1.37 → 192.168.1.97 TLSv1.3 176 Change Cipher Spec, Application Data, Application Data
```
